
package formulaire.Immobilisation;
import comptamatiere.ARTICLE;
import comptamatiere.IMMOBILISATIONMATERIELS;
import comptamatiere.REPORT;
import control.Controle;
import formulaire.Utilisateur.Utilisateur;
import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class MaterielEnservice extends javax.swing.JDialog {
   String reqpart="select idIMMOBILISATIONMATERIEL,LIBARTICLE,utilisateur,CODEMATERIEL,libetat,libbur,categorie.dureevie,DMS,DATACQ,libservice from etat,immobilisationmateriel,article,categorie,bureau,service,utilisateur "
           + "where service.idservice=bureau.idservice and BUREAU.idbureau=IMMOBILISATIONMATERIEL.idbureau AND immobilisationmateriel.idarticle=article.idarticle and article.idcategorie=categorie.idcategorie and immobilisationmateriel.etat=etat.idetat"
           + " and situationMateriel<>'reforme'and immobilisationmateriel.idutilisateur=utilisateur.idutilisateur";
   String requete;
    public MaterielEnservice(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    ARTICLE a= new ARTICLE();
    ArrayList alService=null, alBureau=null ;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnimprimer = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        pnBureau = new javax.swing.JPanel();
        ComboSer = new javax.swing.JComboBox();
        comboBureau = new javax.swing.JComboBox();
        CodeService = new javax.swing.JTextField();
        CodeBure = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblRechercher = new javax.swing.JLabel();
        txtComptePrincipal = new javax.swing.JTextField();
        cmbSearch = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ckBureau = new javax.swing.JCheckBox();
        ckTtInfo = new javax.swing.JCheckBox();
        jPanel12 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMaterielService = new javax.swing.JTable();
        lblbur = new javax.swing.JLabel();
        lblservice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opération", 2, 2, new java.awt.Font("Andalus", 1, 14))); // NOI18N

        jButton1.setText("Fiche Détenteur");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnimprimer.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        btnimprimer.setText("Imprimer");
        btnimprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimerActionPerformed(evt);
            }
        });

        jButton7.setText("Table Utilisateur");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnimprimer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnimprimer)
                .addContainerGap())
        );

        pnBureau.setBackground(new java.awt.Color(255, 255, 255));
        pnBureau.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))), "Service-Bureau", 2, 2, new java.awt.Font("Tempus Sans ITC", 1, 12), new java.awt.Color(0, 102, 255))); // NOI18N

        ComboSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboSerActionPerformed(evt);
            }
        });

        comboBureau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBureauActionPerformed(evt);
            }
        });

        CodeService.setEditable(false);
        CodeService.setForeground(new java.awt.Color(255, 0, 0));
        CodeService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeServiceActionPerformed(evt);
            }
        });

        CodeBure.setEditable(false);
        CodeBure.setForeground(new java.awt.Color(255, 0, 0));
        CodeBure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeBureActionPerformed(evt);
            }
        });

        jLabel2.setText("Ser.");

        jLabel6.setText("Bur.");

        javax.swing.GroupLayout pnBureauLayout = new javax.swing.GroupLayout(pnBureau);
        pnBureau.setLayout(pnBureauLayout);
        pnBureauLayout.setHorizontalGroup(
            pnBureauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBureauLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBureauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnBureauLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addGap(10, 10, 10)
                .addGroup(pnBureauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBureauLayout.createSequentialGroup()
                        .addComponent(ComboSer, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(comboBureau, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBureauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CodeService, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(CodeBure))
                .addContainerGap())
        );
        pnBureauLayout.setVerticalGroup(
            pnBureauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBureauLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnBureauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodeService))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBureauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBureau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(CodeBure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "RECHERCHE", 1, 2, new java.awt.Font("Wide Latin", 1, 10), java.awt.Color.black)); // NOI18N

        lblRechercher.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRechercher.setText("CODEMATERIE");

        txtComptePrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 2, true));
        txtComptePrincipal.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtComptePrincipalCaretUpdate(evt);
            }
        });

        cmbSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CODEMATERIEL", "BUREAU", "LIBARTICLE", "LIBETAT", "UTILISATEUR", " " }));
        cmbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSearchActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1617.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Critère:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtComptePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRechercher))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComptePrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ckBureau.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        ckBureau.setText("Par Bureau");
        ckBureau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckBureauActionPerformed(evt);
            }
        });

        ckTtInfo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        ckTtInfo.setText("Toutes les immobilisations");
        ckTtInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckTtInfoActionPerformed(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(72, 207, 173));
        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Immo", 1, 2, new java.awt.Font("Andalus", 1, 14))); // NOI18N

        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jButton5.setText("Ajouter");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jButton6.setText("Supprimer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton6))
        );

        jLabel1.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        jLabel1.setText("Service:");

        jLabel4.setFont(new java.awt.Font("Vani", 1, 14)); // NOI18N
        jLabel4.setText("Bureau:");

        jPanel14.setBackground(new java.awt.Color(72, 207, 173));
        jPanel14.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(255, 255, 255)));

        jButton14.setBackground(new java.awt.Color(255, 255, 255));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Materiels en service");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton14)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap())
        );

        tableMaterielService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Designation", "Immatriculation", "Etat", "Bureau", "Utilisateur", "Categorie", "Cpte Nom.", "Date MS", "Date Acq"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMaterielService.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableMaterielService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMaterielServiceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMaterielService);

        lblbur.setFont(new java.awt.Font("Vani", 3, 14)); // NOI18N
        lblbur.setForeground(new java.awt.Color(153, 0, 0));
        lblbur.setText("Service:");

        lblservice.setFont(new java.awt.Font("Vani", 3, 14)); // NOI18N
        lblservice.setForeground(new java.awt.Color(153, 0, 0));
        lblservice.setText("Service:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnBureau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(ckTtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ckBureau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblservice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblbur))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(287, 287, 287))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckTtInfo)
                            .addComponent(ckBureau))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnBureau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(lblbur)
                    .addComponent(lblservice, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-833)/2, (screenSize.height-726)/2, 833, 726);
    }// </editor-fold>//GEN-END:initComponents
IMMOBILISATIONMATERIELS s= new IMMOBILISATIONMATERIELS(); 
    private void chargement(){
        try {
            tableMaterielService.setModel(s.getDefaulTableModel(reqpart));
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try { 
            lblbur.setText("");
            lblservice.setText("");
            // chargement de combo
            alService = a.getComboELement("select idservice,LIBSERVICE from service order by LIBSERVICE",ComboSer);    
            a.viderJtable(tableMaterielService);   
             chargement();
             
              tableMaterielService.getColumn("idIMMOBILISATIONMATERIEL").setMinWidth(0);
               tableMaterielService.getColumn("idIMMOBILISATIONMATERIEL").setPreferredWidth(0);
               tableMaterielService.getColumn("idIMMOBILISATIONMATERIEL").setMaxWidth(0);

                tableMaterielService.getColumn("dureevie").setMinWidth(0);
               tableMaterielService.getColumn("dureevie").setPreferredWidth(0);
               tableMaterielService.getColumn("dureevie").setMaxWidth(0);
               
               tableMaterielService.getColumn("LIBARTICLE").setMinWidth(50);
               tableMaterielService.getColumn("LIBARTICLE").setPreferredWidth(350);
               tableMaterielService.getColumn("LIBARTICLE").setMaxWidth(350);
               
               tableMaterielService.getColumn("CODEMATERIEL").setMinWidth(50);
               tableMaterielService.getColumn("CODEMATERIEL").setPreferredWidth(300);
               tableMaterielService.getColumn("CODEMATERIEL").setMaxWidth(400);
               
               
               tableMaterielService.getColumn("utilisateur").setMinWidth(30);
               tableMaterielService.getColumn("utilisateur").setPreferredWidth(190);
               tableMaterielService.getColumn("utilisateur").setMaxWidth(190);
               
               tableMaterielService.getColumn("libbur").setMinWidth(20);
               tableMaterielService.getColumn("libbur").setPreferredWidth(200);
               tableMaterielService.getColumn("libbur").setMaxWidth(400);
              // tableMaterielService.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
              // new JScrollPane(tableMaterielService,JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
               //tableMaterielService.setPreferredScrollableViewportSize(Toolkit.getDefaultToolkit().getScreenSize());
               
    } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
       
    }//GEN-LAST:event_formComponentShown

    private void ComboSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboSerActionPerformed
        lblservice.setText(ComboSer.getSelectedItem().toString());
        lblbur.setText("");
        try {
            //Service.setText(ALSERVICE.get(ComboSer.getSelectedIndex()).toString());
            CodeService.setText(alService.get(ComboSer.getSelectedIndex()).toString());
            CodeBure.setText(null);
            alBureau=a.getComboELement("select idbureau,libbur from bureau where idservice="+CodeService.getText()+" order by libbur",comboBureau);
             CodeBure.setText(alBureau.get(comboBureau.getSelectedIndex()).toString());
            requete=reqpart+" and IMMOBILISATIONMATERIEL.IDBUREAU in (select idbureau from bureau where idservice="+CodeService.getText()+") order by libservice,libbur,utilisateur";
         s.setRemplirJtable(tableMaterielService,requete); 
  
            CodeBure.setText("");
            btnimprimer.setText("Imprimer par Service");
           // comboBureau.setSelectedIndex("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    }//GEN-LAST:event_ComboSerActionPerformed

    private void comboBureauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBureauActionPerformed
        lblbur.setText(comboBureau.getSelectedItem().toString());
        CodeBure.setText(alBureau.get(comboBureau.getSelectedIndex()).toString());
        try {
         requete= reqpart+" and IMMOBILISATIONMATERIEL.IDBUREAU="+CodeBure.getText()+" order by libservice,libbur,utilisateur";
         s.setRemplirJtable(tableMaterielService,requete); 
         btnimprimer.setText("Imprimer par bureau");
         
          tableMaterielService.getColumn("idIMMOBILISATIONMATERIEL").setMinWidth(0);
               tableMaterielService.getColumn("idIMMOBILISATIONMATERIEL").setPreferredWidth(0);
               tableMaterielService.getColumn("idIMMOBILISATIONMATERIEL").setMaxWidth(0);
               
               
                tableMaterielService.getColumn("budget").setMinWidth(0);
               tableMaterielService.getColumn("budget").setPreferredWidth(0);
               tableMaterielService.getColumn("budget").setMaxWidth(0);
               
                tableMaterielService.getColumn("dureevie").setMinWidth(0);
               tableMaterielService.getColumn("dureevie").setPreferredWidth(0);
               tableMaterielService.getColumn("dureevie").setMaxWidth(0);
               
               tableMaterielService.getColumn("LIBARTICLE").setMinWidth(50);
               tableMaterielService.getColumn("LIBARTICLE").setPreferredWidth(350);
               tableMaterielService.getColumn("LIBARTICLE").setMaxWidth(350);
               
               tableMaterielService.getColumn("CODEMATERIEL").setMinWidth(50);
               tableMaterielService.getColumn("CODEMATERIEL").setPreferredWidth(300);
               tableMaterielService.getColumn("CODEMATERIEL").setMaxWidth(400);
               
               
               tableMaterielService.getColumn("utilisateur").setMinWidth(30);
               tableMaterielService.getColumn("utilisateur").setPreferredWidth(190);
               tableMaterielService.getColumn("utilisateur").setMaxWidth(190);
               
               tableMaterielService.getColumn("libbur").setMinWidth(20);
               tableMaterielService.getColumn("libbur").setPreferredWidth(200);
               tableMaterielService.getColumn("libbur").setMaxWidth(400);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this,ex.getMessage());
        }       
    }//GEN-LAST:event_comboBureauActionPerformed

    private void CodeBureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeBureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodeBureActionPerformed

    private void txtComptePrincipalCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtComptePrincipalCaretUpdate
        if(txtComptePrincipal.getText()!=""){
                String a= cmbSearch.getSelectedItem().toString();
                if(a.equals("BUREAU"))
                    a="libbur";
            try {
                s.setRemplirJtable(tableMaterielService,reqpart+ " and "+a +" like '%"+txtComptePrincipal.getText()+"%'");
               tableMaterielService.getColumn("idIMMOBILISATIONMATERIEL").setMinWidth(0);
               tableMaterielService.getColumn("idIMMOBILISATIONMATERIEL").setPreferredWidth(0);
               tableMaterielService.getColumn("idIMMOBILISATIONMATERIEL").setMaxWidth(0);
               
               
                tableMaterielService.getColumn("budget").setMinWidth(0);
               tableMaterielService.getColumn("budget").setPreferredWidth(0);
               tableMaterielService.getColumn("budget").setMaxWidth(0);
               
                tableMaterielService.getColumn("dureevie").setMinWidth(0);
               tableMaterielService.getColumn("dureevie").setPreferredWidth(0);
               tableMaterielService.getColumn("dureevie").setMaxWidth(0);
               
               tableMaterielService.getColumn("LIBARTICLE").setMinWidth(50);
               tableMaterielService.getColumn("LIBARTICLE").setPreferredWidth(350);
               tableMaterielService.getColumn("LIBARTICLE").setMaxWidth(350);
               
               tableMaterielService.getColumn("CODEMATERIEL").setMinWidth(50);
               tableMaterielService.getColumn("CODEMATERIEL").setPreferredWidth(300);
               tableMaterielService.getColumn("CODEMATERIEL").setMaxWidth(400);
               
               
               tableMaterielService.getColumn("utilisateur").setMinWidth(30);
               tableMaterielService.getColumn("utilisateur").setPreferredWidth(190);
               tableMaterielService.getColumn("utilisateur").setMaxWidth(190);
               
               tableMaterielService.getColumn("libbur").setMinWidth(20);
               tableMaterielService.getColumn("libbur").setPreferredWidth(200);
               tableMaterielService.getColumn("libbur").setMaxWidth(400);
               tableMaterielService.setDefaultEditor(Object.class, null);
               //tableMaterielService.isCellEditable(1, 1);
        } catch (SQLException ex) {
        }
        }
    }//GEN-LAST:event_txtComptePrincipalCaretUpdate

    private void cmbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSearchActionPerformed
        lblRechercher.setText(cmbSearch.getSelectedItem().toString());
    }//GEN-LAST:event_cmbSearchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ckTtInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckTtInfoActionPerformed
        CodeBure.setText("");
        CodeService.setText("");
        requete=reqpart;
        if(ckTtInfo.getModel().isSelected()){
           ckBureau.getModel().setSelected(false);
         for(Component c:pnBureau.getComponents())
             c.setEnabled(false);
        }
    }//GEN-LAST:event_ckTtInfoActionPerformed

    private void ckBureauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckBureauActionPerformed
        ckTtInfo.getModel().setSelected(false);
        if(ckBureau.getModel().isSelected())
        for(Component c:pnBureau.getComponents())
             c.setEnabled(true);   
    }//GEN-LAST:event_ckBureauActionPerformed

    private void tableMaterielServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMaterielServiceMouseClicked
        immoselect=tableMaterielService.getValueAt(tableMaterielService.getSelectedRow(),s.getColumnByName(tableMaterielService,"idimmobilisationmateriel")).toString();
    }//GEN-LAST:event_tableMaterielServiceMouseClicked
      String immoselect;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         Modification m= new Modification(new JFrame(),true);
        try{          
            m.idimmobilisation= immoselect;
         // JOptionPane.showMessageDialog(this, immoselect);
            m.setVisible(true);
        }catch(IndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(this,"Choisissez une immobilisation à modifier");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        NouveauExistant n= new NouveauExistant(new JFrame(),true);
        n.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       if(JOptionPane.showConfirmDialog(this,"Suppression de l\'enrégistrement sélectionné?","suppression",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
            try{
              JOptionPane.showMessageDialog(this, a.insUpdateDel("delete from immobilisationmateriel where idimmobilisationmateriel="+immoselect)+" immobilisation supprimée");
              chargement();
               tableMaterielService.getColumn("idIMMOBILISATIONMATERIEL").setMinWidth(0);
               tableMaterielService.getColumn("idIMMOBILISATIONMATERIEL").setPreferredWidth(0);
               tableMaterielService.getColumn("idIMMOBILISATIONMATERIEL").setMaxWidth(0);
               
               
                tableMaterielService.getColumn("budget").setMinWidth(0);
               tableMaterielService.getColumn("budget").setPreferredWidth(0);
               tableMaterielService.getColumn("budget").setMaxWidth(0);
               
                tableMaterielService.getColumn("dureevie").setMinWidth(0);
               tableMaterielService.getColumn("dureevie").setPreferredWidth(0);
               tableMaterielService.getColumn("dureevie").setMaxWidth(0);
               
               tableMaterielService.getColumn("LIBARTICLE").setMinWidth(50);
               tableMaterielService.getColumn("LIBARTICLE").setPreferredWidth(350);
               tableMaterielService.getColumn("LIBARTICLE").setMaxWidth(350);
               
               tableMaterielService.getColumn("CODEMATERIEL").setMinWidth(50);
               tableMaterielService.getColumn("CODEMATERIEL").setPreferredWidth(300);
               tableMaterielService.getColumn("CODEMATERIEL").setMaxWidth(400);
               
               
               tableMaterielService.getColumn("utilisateur").setMinWidth(30);
               tableMaterielService.getColumn("utilisateur").setPreferredWidth(190);
               tableMaterielService.getColumn("utilisateur").setMaxWidth(190);
               
               tableMaterielService.getColumn("libbur").setMinWidth(20);
               tableMaterielService.getColumn("libbur").setPreferredWidth(200);
               tableMaterielService.getColumn("libbur").setMaxWidth(400);
               tableMaterielService.setDefaultEditor(Object.class, null);
            }catch(IndexOutOfBoundsException ex){
                   JOptionPane.showMessageDialog(this,"Choisissez une immobilisation à supprimer");
           }catch(SQLException exe){
                JOptionPane.showMessageDialog(this,"Suppression impossible");
           }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FicheDetenteurMateriel fiche= new FicheDetenteurMateriel(new JFrame(),true);
        fiche.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        if(Controle.modification){
             chargement();
             tableMaterielService.getColumn("idIMMOBILISATIONMATERIEL").setMinWidth(0);
               tableMaterielService.getColumn("idIMMOBILISATIONMATERIEL").setPreferredWidth(0);
               tableMaterielService.getColumn("idIMMOBILISATIONMATERIEL").setMaxWidth(0);
               
                tableMaterielService.getColumn("dureevie").setMinWidth(0);
               tableMaterielService.getColumn("dureevie").setPreferredWidth(0);
               tableMaterielService.getColumn("dureevie").setMaxWidth(0);
               
               tableMaterielService.getColumn("LIBARTICLE").setMinWidth(50);
               tableMaterielService.getColumn("LIBARTICLE").setPreferredWidth(350);
               tableMaterielService.getColumn("LIBARTICLE").setMaxWidth(350);
               
               tableMaterielService.getColumn("CODEMATERIEL").setMinWidth(50);
               tableMaterielService.getColumn("CODEMATERIEL").setPreferredWidth(300);
               tableMaterielService.getColumn("CODEMATERIEL").setMaxWidth(400);
               
               
               tableMaterielService.getColumn("utilisateur").setMinWidth(30);
               tableMaterielService.getColumn("utilisateur").setPreferredWidth(190);
               tableMaterielService.getColumn("utilisateur").setMaxWidth(190);
               
               tableMaterielService.getColumn("libbur").setMinWidth(20);
               tableMaterielService.getColumn("libbur").setPreferredWidth(200);
               tableMaterielService.getColumn("libbur").setMaxWidth(400);
             Controle.modification=false;
             tableMaterielService.setDefaultEditor(Object.class, null);
                    
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Utilisateur u= new Utilisateur(new JFrame(),true);
        u.setVisible(true);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void CodeServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodeServiceActionPerformed

    private void btnimprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimerActionPerformed
        REPORT e = new REPORT();
        try {
               e.editionReport("materielenservice", requete, e.getInstitutionMap());
           } catch (Exception ex) {
              JOptionPane.showMessageDialog(this,"Erreur d\'impression "+ ex.getMessage());
           }
    }//GEN-LAST:event_btnimprimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaterielEnservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaterielEnservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaterielEnservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaterielEnservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MaterielEnservice dialog = new MaterielEnservice(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodeBure;
    private javax.swing.JTextField CodeService;
    private javax.swing.JComboBox ComboSer;
    private javax.swing.JButton btnimprimer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JCheckBox ckBureau;
    private javax.swing.JCheckBox ckTtInfo;
    private javax.swing.JComboBox cmbSearch;
    private javax.swing.JComboBox comboBureau;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRechercher;
    private javax.swing.JLabel lblbur;
    private javax.swing.JLabel lblservice;
    private javax.swing.JPanel pnBureau;
    private javax.swing.JTable tableMaterielService;
    private javax.swing.JTextField txtComptePrincipal;
    // End of variables declaration//GEN-END:variables
}
