
package formulaire.Immobilisation;

import comptamatiere.IMMOBILISATIONMATERIELS;
import control.Controle;
import formulaire.article.Article;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class NouveauAttente extends javax.swing.JDialog {

  IMMOBILISATIONMATERIELS imo=new IMMOBILISATIONMATERIELS();
  ArrayList alU,alE,alB;
  //public String Service,libureau,idBureau;
  String idcat,codi,numsuivant,iddetailsortie,idbur;
  String reqpart="select detailsortie.idARTICLE as Code,LIBARTICLE as Article,budget.idbudget,detailsortie.nonattribue,"
          + "categorie.codeicat,detailsortie.idsortie as Sortie,detailsortie.pu_sortie,detailsortie.iddetailsortie,categorie.idcategorie,sortie.idbureau,bureau.libbur as Bureau,DATESORTIE, detailsortie.type,Bon.idbon as Entree from article,categorie,detailsortie,sortie,detailbon,bon,budget,bureau"
          + " where detailsortie.immo=1 and detailsortie.idsortie=sortie.idsortie and sortie.valide=1 and sortie.idbureau=bureau.idbureau and article.idcategorie=categorie.idcategorie and article.idarticle=detailsortie.idarticle"+
          " and detailsortie.iddetailbon=detailbon.iddetailbon and detailbon.idbon=bon.idbon and bon.idbudget=budget.idbudget and nonattribue>0 ";
  
    public NouveauAttente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setBackground(Color.white);
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    String idbudget;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableArticle = new javax.swing.JTable();
        lblRechercher = new javax.swing.JLabel();
        txtComptePrincipal = new javax.swing.JTextField();
        cmbSearch = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        libarticle = new javax.swing.JTextField();
        Montant = new javax.swing.JTextField();
        cmbEtat = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sigle = new javax.swing.JTextField();
        idarticle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDatEnservice = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCodeImmo = new javax.swing.JTextField();
        Sexe = new javax.swing.JLabel();
        idEtat = new javax.swing.JTextField();
        txtDateAquis = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bureau = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ComboListUtilisateur = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        utilisateur = new javax.swing.JTextField();
        idsortie = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        idbudgetentree = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Materiel Pour Affectation", 2, 2, new java.awt.Font("Tempus Sans ITC", 1, 14), java.awt.Color.black)); // NOI18N

        tableArticle.setAutoCreateRowSorter(true);
        tableArticle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null}
            },
            new String [] {
                "Titre 1"
            }
        ));
        tableArticle.setName("tableArticle"); // NOI18N
        tableArticle.setSelectionForeground(new java.awt.Color(204, 0, 0));
        tableArticle.getTableHeader().setReorderingAllowed(false);
        tableArticle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableArticleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableArticle);

        lblRechercher.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblRechercher.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRechercher.setText("Article");

        txtComptePrincipal.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtComptePrincipalCaretUpdate(evt);
            }
        });
        txtComptePrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComptePrincipalActionPerformed(evt);
            }
        });

        cmbSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "IDARTICLE", "IDSORTIE", "LIBARTICLE", "LIBBUR" }));
        cmbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSearchActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel15.setText("Rechercher Par :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lblRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtComptePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComptePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRechercher)
                    .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel4.setBackground(new java.awt.Color(79, 193, 233));

        libarticle.setEditable(false);

        Montant.setEditable(false);
        Montant.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Montant.setForeground(new java.awt.Color(0, 51, 255));
        Montant.setAutoscrolls(false);
        Montant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontantActionPerformed(evt);
            }
        });

        cmbEtat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEtatActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Imm.");

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Date MS");

        sigle.setEditable(false);
        sigle.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sigle.setForeground(new java.awt.Color(0, 51, 255));
        sigle.setAutoscrolls(false);

        idarticle.setEditable(false);
        idarticle.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        idarticle.setForeground(new java.awt.Color(0, 51, 255));
        idarticle.setAutoscrolls(false);
        idarticle.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                idarticleCaretUpdate(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Prix");

        txtDatEnservice.setDateFormatString("dd/MM/yyyy");
        txtDatEnservice.setFocusable(false);
        txtDatEnservice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDatEnserviceMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Budget");

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Etat");

        txtCodeImmo.setEditable(false);
        txtCodeImmo.setBackground(new java.awt.Color(255, 204, 204));
        txtCodeImmo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCodeImmo.setAutoscrolls(false);
        txtCodeImmo.setFocusable(false);
        txtCodeImmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeImmoActionPerformed(evt);
            }
        });

        Sexe.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        Sexe.setForeground(new java.awt.Color(255, 255, 255));
        Sexe.setText("Materiel");

        idEtat.setEditable(false);
        idEtat.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        idEtat.setForeground(new java.awt.Color(0, 51, 255));
        idEtat.setAutoscrolls(false);

        txtDateAquis.setEditable(false);
        txtDateAquis.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtDateAquis.setForeground(new java.awt.Color(0, 51, 255));
        txtDateAquis.setAutoscrolls(false);
        txtDateAquis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateAquisActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Date Acquisition");

        jButton2.setText("Enrégistrer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bureau");

        bureau.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Liste utilisateurs");

        ComboListUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboListUtilisateurActionPerformed(evt);
            }
        });

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("code utilisateur");

        utilisateur.setEditable(false);

        idsortie.setEditable(false);
        idsortie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idsortie.setForeground(new java.awt.Color(153, 0, 0));

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Ordre Sortie:");

        idbudgetentree.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sexe, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bureau, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(libarticle, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(idarticle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(cmbEtat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(idEtat, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(sigle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(8, 8, 8))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(idbudgetentree, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCodeImmo))
                                        .addGap(27, 27, 27)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDateAquis))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Montant)
                                            .addComponent(idsortie)
                                            .addComponent(utilisateur)
                                            .addComponent(txtDatEnservice, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(ComboListUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(bureau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idsortie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboListUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jButton1)
                    .addComponent(jLabel6)
                    .addComponent(utilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(libarticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Sexe)
                        .addComponent(idarticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDatEnservice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEtat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idEtat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sigle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Montant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idbudgetentree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodeImmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateAquis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE))
                .addGap(96, 96, 96))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(79, 193, 233));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(255, 255, 255)));

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Table des articles");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 488, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-908)/2, (screenSize.height-670)/2, 908, 670);
    }// </editor-fold>//GEN-END:initComponents

    private void ComboListUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboListUtilisateurActionPerformed
       // JOptionPane.showConfirmDialog(this, "present");
        //Service.setText(ALSERVICE.get(ComboSer.getSelectedIndex()).toString());
        utilisateur.setText(alU.get(ComboListUtilisateur.getSelectedIndex()).toString());
        //utilisateur.setText(CollUtilisateur.get(ComboListUtilisateur.getSelectedItem()).toString());
    }//GEN-LAST:event_ComboListUtilisateurActionPerformed

    private void txtCodeImmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeImmoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeImmoActionPerformed

    private void txtDatEnserviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDatEnserviceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatEnserviceMouseClicked

    private void MontantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MontantActionPerformed

    private void cmbEtatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEtatActionPerformed
        idEtat.setText(alE.get(cmbEtat.getSelectedIndex()).toString());
    }//GEN-LAST:event_cmbEtatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(idarticle.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "choisissez l\'article à attribuer");
        else if(txtDatEnservice.getDate()==null){
            JOptionPane.showMessageDialog(this,"saisissez la date de mise en service");
        } else if(utilisateur.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Choisissez l\'ulilisateur concerné");
            //ComboListUtilisateur.setFocusable(true);
            //ComboListUtilisateur.setForeground(Color.red); 
        }
        
        else{
            int reponse= JOptionPane.showConfirmDialog(this,"voulez-vous enregistrez?","confirmation",JOptionPane.YES_NO_OPTION);
            if(reponse==JOptionPane.YES_OPTION){
                try {
                    String valeur[]={idarticle.getText(),txtCodeImmo.getText(),idcat,numsuivant,imo.getDateChoisie(txtDatEnservice),
                        Montant.getText(),idEtat.getText(),sigle.getText(),idbur,utilisateur.getText(),txtDateAquis.getText(),iddetailsortie};
                    int j= imo.Insertion("IMMOBILISATIONMATERIEL(IDARTICLE,CODEMATERIEL,IDCATEGORIE,NUMERO,DMS,PUACQ,ETAT,budget,IDBUREAU,IDUTILISATEUR,datacq,iddetailsortie)", valeur);

                    JOptionPane.showMessageDialog(this, j+" Immobilisation engistrée");
                    if(j==1){
                        //mis à jour du reste à attribuer
                        imo.insUpdateDel("update detailsortie set nonattribue=nonattribue-1 where iddetailsortie="+iddetailsortie);
                        iddetailsortie=null;
                        // CodeBure.setText(null);
                        libarticle.setText(null);
                        txtCodeImmo.setText(null);
                        Montant.setText(null);
                        txtDatEnservice.setDate(null);
                        Controle.modification=true;
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this,ex.getMessage());
                }

            }
       }
    }//GEN-LAST:event_jButton2ActionPerformed
     
    private void tableArticleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableArticleMouseClicked
        idarticle.setText("");libarticle.setText("");txtCodeImmo.setText("");
        
        try {
            idbur=tableArticle.getValueAt(tableArticle.getSelectedRow(),imo.getColumnByName(tableArticle,"idbureau")).toString();
            bureau.setText(tableArticle.getValueAt(tableArticle.getSelectedRow(),imo.getColumnByName(tableArticle,"Bureau")).toString());
            //chargement des utilisateurs du bureau
             alU=imo.getComboELement("select idutilisateur,utilisateur from utilisateur where idbureau="+idbur, ComboListUtilisateur);
             utilisateur.setText(alU.get(ComboListUtilisateur.getSelectedIndex()).toString());
             idbudget=tableArticle.getValueAt(tableArticle.getSelectedRow(),imo.getColumnByName(tableArticle,"idbudget")).toString();
             idbudgetentree.setText(tableArticle.getValueAt(tableArticle.getSelectedRow(),imo.getColumnByName(tableArticle,"idbudget")).toString());
            
            idcat=tableArticle.getValueAt(tableArticle.getSelectedRow(),imo.getColumnByName(tableArticle,"idcategorie")).toString();
            codi=tableArticle.getValueAt(tableArticle.getSelectedRow(),imo.getColumnByName(tableArticle,"codeicat")).toString();
            idarticle.setText(tableArticle.getValueAt(tableArticle.getSelectedRow(),imo.getColumnByName(tableArticle,"Code")).toString());
            libarticle.setText(tableArticle.getValueAt(tableArticle.getSelectedRow(),imo.getColumnByName(tableArticle,"Article")).toString());
            String idSortie=tableArticle.getValueAt(tableArticle.getSelectedRow(),imo.getColumnByName(tableArticle,"Sortie")).toString();
            idsortie.setText(idSortie);
            numsuivant=imo.getMaxNumSuivant(idcat);
            sigle.setText(imo.getOneResult("select sigle from budget where idbudget="+idbudget));
            txtCodeImmo.setText(imo.getCodeImmo(numsuivant, codi, idbur,sigle.getText()));
            iddetailsortie=tableArticle.getValueAt(tableArticle.getSelectedRow(),imo.getColumnByName(tableArticle,"iddetailsortie")).toString();
            Montant.setText(tableArticle.getValueAt(tableArticle.getSelectedRow(),imo.getColumnByName(tableArticle,"pu_sortie")).toString());
            txtDateAquis.setText(imo.getDateAqui(iddetailsortie,idarticle.getText(),tableArticle.getValueAt(tableArticle.getSelectedRow(),imo.getColumnByName(tableArticle,"type")).toString()));
           // txtDateEnservice.
            String dateService=tableArticle.getValueAt(tableArticle.getSelectedRow(),imo.getColumnByName(tableArticle,"Datesortie")).toString();
            try {
                imo.setAfficherDate(txtDatEnservice, dateService);
                       // imo.setAfficherDate(txtDatEnservice, imo.tableArticle.getSelectedRow(),imo.getColumnByName(tableArticle,"pu_sortie")).toString());
            } catch (ParseException ex) {
                Logger.getLogger(NouveauAttente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    }//GEN-LAST:event_tableArticleMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
               // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void txtComptePrincipalCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtComptePrincipalCaretUpdate
        if(txtComptePrincipal.getText()!=""){
            String a="";
          if(txtComptePrincipal.getText()!="idarticle")
              a="LIBARTICLE.";
            try {
                tableArticle.setModel(imo.getDefaulTableModel(reqpart+ " and "+  a+cmbSearch.getSelectedItem().toString() +" like '%"+txtComptePrincipal.getText()+"%'"));
              
            } catch (SQLException ex) {
            }
        }
       tableArticle.getColumn("idbudget").setMinWidth(0);
       tableArticle.getColumn("idbudget").setPreferredWidth(0);
       tableArticle.getColumn("idbudget").setMaxWidth(0);
       
       tableArticle.getColumn("codeicat").setMinWidth(0);
       tableArticle.getColumn("codeicat").setPreferredWidth(0);
       tableArticle.getColumn("codeicat").setMaxWidth(0);
      
       tableArticle.getColumn("idbureau").setMinWidth(0);
       tableArticle.getColumn("idbureau").setPreferredWidth(0);
       tableArticle.getColumn("idbureau").setMaxWidth(0);
       
       tableArticle.getColumn("iddetailsortie").setMinWidth(0);
       tableArticle.getColumn("iddetailsortie").setPreferredWidth(0);
       tableArticle.getColumn("iddetailsortie").setMaxWidth(0);
       
       tableArticle.getColumn("type").setMinWidth(0);
       tableArticle.getColumn("type").setPreferredWidth(0);
       tableArticle.getColumn("type").setMaxWidth(0);
      
       tableArticle.getColumn("idcategorie").setMinWidth(0);
       tableArticle.getColumn("idcategorie").setPreferredWidth(0);
       tableArticle.getColumn("idcategorie").setMaxWidth(0);
       
       tableArticle.getColumn("Code").setMinWidth(40);
       tableArticle.getColumn("Code").setPreferredWidth(40);
       tableArticle.getColumn("Code").setMaxWidth(40);
       
       tableArticle.getColumn("nonattribue").setMinWidth(40);
       tableArticle.getColumn("nonattribue").setPreferredWidth(40);
       tableArticle.getColumn("nonattribue").setMaxWidth(40);
       
       
       tableArticle.getColumn("Sortie").setMinWidth(50);
       tableArticle.getColumn("Sortie").setPreferredWidth(50);
       tableArticle.getColumn("Sortie").setMaxWidth(50);
       
       tableArticle.getColumn("Entree").setMinWidth(50);
       tableArticle.getColumn("Entree").setPreferredWidth(50);
       tableArticle.getColumn("Entree").setMaxWidth(50);
       
        tableArticle.getColumn("DATESORTIE").setMinWidth(100);
       tableArticle.getColumn("DATESORTIE").setPreferredWidth(100);
       tableArticle.getColumn("DATESORTIE").setMaxWidth(100);
       
       tableArticle.getColumn("pu_sortie").setMinWidth(100);
       tableArticle.getColumn("pu_sortie").setPreferredWidth(100);
       tableArticle.getColumn("pu_sortie").setMaxWidth(100);
    }//GEN-LAST:event_txtComptePrincipalCaretUpdate

    private void cmbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSearchActionPerformed
        lblRechercher.setText(cmbSearch.getSelectedItem().toString());
    }//GEN-LAST:event_cmbSearchActionPerformed

    private void idarticleCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_idarticleCaretUpdate
       // TODO add your handling code here:
    }//GEN-LAST:event_idarticleCaretUpdate

    private void txtComptePrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComptePrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComptePrincipalActionPerformed

    private void txtDateAquisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateAquisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateAquisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      formulaire.Utilisateur.Nouveau n= new formulaire.Utilisateur.Nouveau(new JFrame(),true);
       n.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
try {
          alE=imo.getComboELement("select idetat,libetat from etat", cmbEtat);
          idEtat.setText(alE.get(cmbEtat.getSelectedIndex()).toString());
          
          //remplissage de jtable de selection
          tableArticle.setModel(imo.getDefaulTableModel(reqpart)); 
          //tableArticle.getColumn(idarticle).
          //bureau.setText(libureau);
       tableArticle.getColumn("idbudget").setMinWidth(0);
       tableArticle.getColumn("idbudget").setPreferredWidth(0);
       tableArticle.getColumn("idbudget").setMaxWidth(0);
       
       tableArticle.getColumn("codeicat").setMinWidth(0);
       tableArticle.getColumn("codeicat").setPreferredWidth(0);
       tableArticle.getColumn("codeicat").setMaxWidth(0);
      
       tableArticle.getColumn("idbureau").setMinWidth(0);
       tableArticle.getColumn("idbureau").setPreferredWidth(0);
       tableArticle.getColumn("idbureau").setMaxWidth(0);
       
       tableArticle.getColumn("iddetailsortie").setMinWidth(0);
       tableArticle.getColumn("iddetailsortie").setPreferredWidth(0);
       tableArticle.getColumn("iddetailsortie").setMaxWidth(0);
       
       tableArticle.getColumn("type").setMinWidth(0);
       tableArticle.getColumn("type").setPreferredWidth(0);
       tableArticle.getColumn("type").setMaxWidth(0);
      
       tableArticle.getColumn("idcategorie").setMinWidth(0);
       tableArticle.getColumn("idcategorie").setPreferredWidth(0);
       tableArticle.getColumn("idcategorie").setMaxWidth(0);
       
       
       tableArticle.getColumn("Code").setMinWidth(40);
       tableArticle.getColumn("Code").setPreferredWidth(40);
       tableArticle.getColumn("Code").setMaxWidth(40);
       
       tableArticle.getColumn("nonattribue").setMinWidth(40);
       tableArticle.getColumn("nonattribue").setPreferredWidth(40);
       tableArticle.getColumn("nonattribue").setMaxWidth(40);
       
       
       tableArticle.getColumn("Sortie").setMinWidth(50);
       tableArticle.getColumn("Sortie").setPreferredWidth(50);
       tableArticle.getColumn("Sortie").setMaxWidth(50);
       
       tableArticle.getColumn("Entree").setMinWidth(50);
       tableArticle.getColumn("Entree").setPreferredWidth(50);
       tableArticle.getColumn("Entree").setMaxWidth(50);
       
        tableArticle.getColumn("DATESORTIE").setMinWidth(100);
       tableArticle.getColumn("DATESORTIE").setPreferredWidth(100);
       tableArticle.getColumn("DATESORTIE").setMaxWidth(100);
       
       tableArticle.getColumn("pu_sortie").setMinWidth(100);
       tableArticle.getColumn("pu_sortie").setPreferredWidth(100);
       tableArticle.getColumn("pu_sortie").setMaxWidth(100);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }  
        
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            
            java.util.logging.Logger.getLogger(NouveauAttente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NouveauAttente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NouveauAttente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NouveauAttente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NouveauAttente dialog = new NouveauAttente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboListUtilisateur;
    private javax.swing.JTextField Montant;
    private javax.swing.JLabel Sexe;
    private javax.swing.JTextField bureau;
    private javax.swing.JComboBox cmbEtat;
    private javax.swing.JComboBox cmbSearch;
    private javax.swing.JTextField idEtat;
    private javax.swing.JTextField idarticle;
    private javax.swing.JTextField idbudgetentree;
    private javax.swing.JTextField idsortie;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRechercher;
    private javax.swing.JTextField libarticle;
    private javax.swing.JTextField sigle;
    public javax.swing.JTable tableArticle;
    private javax.swing.JTextField txtCodeImmo;
    private javax.swing.JTextField txtComptePrincipal;
    private com.toedter.calendar.JDateChooser txtDatEnservice;
    private javax.swing.JTextField txtDateAquis;
    private javax.swing.JTextField utilisateur;
    // End of variables declaration//GEN-END:variables
}
