
package formulaire.Reforme;

import comptamatiere.AMORTISSEMENT;
import comptamatiere.IMMOBILISATIONMATERIELS;
import comptamatiere.REFORME;
import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class NouveauPropositionReforme extends javax.swing.JDialog {
   String reqpart="select idIMMOBILISATIONMATERIEL,LIBARTICLE as Article,utilisateur,CODEMATERIEL,libetat,libbur as bureau,categorie.dureevie,DMS,DATACQ,immobilisationmateriel.puacq,budget from etat,immobilisationmateriel,article,categorie,bureau,utilisateur "
           + "where immobilisationmateriel.situationmateriel='enservice' and BUREAU.idbureau=IMMOBILISATIONMATERIEL.idbureau AND immobilisationmateriel.idarticle=article.idarticle and article.idcategorie=categorie.idcategorie and immobilisationmateriel.etat=etat.idetat"
           + " and immobilisationmateriel.idutilisateur=utilisateur.idutilisateur";
   String idimmo;
   REFORME r=new REFORME();
   IMMOBILISATIONMATERIELS s= new IMMOBILISATIONMATERIELS(); 
   AMORTISSEMENT a= new AMORTISSEMENT();
    int dema=0;
   public NouveauPropositionReforme(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    ArrayList alService=null, alBureau=null ;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMaterielService = new javax.swing.JTable();
        pnBureau = new javax.swing.JPanel();
        ComboSer = new javax.swing.JComboBox();
        comboBureau = new javax.swing.JComboBox();
        CodeService = new javax.swing.JTextField();
        CodeBure = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblRechercher = new javax.swing.JLabel();
        txtComptePrincipal = new javax.swing.JTextField();
        cmbSearch = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ckBureau = new javax.swing.JCheckBox();
        ckTtInfo = new javax.swing.JCheckBox();
        jPanel12 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtArticle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBur = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMontantacqui = new javax.swing.JTextField();
        txtPrixresi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        datepropoRef = new com.toedter.calendar.JDateChooser();
        dateMs = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtDurevie = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tableMaterielService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Designation", "Immatriculation", "Etat", "Bureau", "Utilisateur", "Categorie", "Cpte Nom.", "Date MS", "Date Acq"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMaterielService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMaterielServiceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMaterielService);

        pnBureau.setBackground(new java.awt.Color(255, 255, 255));
        pnBureau.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))), "Service-Bureau", 2, 2, new java.awt.Font("Tempus Sans ITC", 1, 12), new java.awt.Color(0, 102, 255))); // NOI18N

        ComboSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboSerActionPerformed(evt);
            }
        });

        comboBureau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBureauActionPerformed(evt);
            }
        });

        CodeService.setEditable(false);
        CodeService.setForeground(new java.awt.Color(255, 0, 0));

        CodeBure.setEditable(false);
        CodeBure.setForeground(new java.awt.Color(255, 0, 0));
        CodeBure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeBureActionPerformed(evt);
            }
        });

        jLabel2.setText("Ser.");

        jLabel6.setText("Bur.");

        javax.swing.GroupLayout pnBureauLayout = new javax.swing.GroupLayout(pnBureau);
        pnBureau.setLayout(pnBureauLayout);
        pnBureauLayout.setHorizontalGroup(
            pnBureauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBureauLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(ComboSer, 0, 362, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CodeService, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBureau, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CodeBure, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnBureauLayout.setVerticalGroup(
            pnBureauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBureauLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnBureauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodeService)
                    .addComponent(comboBureau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(CodeBure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "RECHERCHE", 1, 2, new java.awt.Font("Wide Latin", 1, 10), java.awt.Color.black)); // NOI18N

        lblRechercher.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRechercher.setText("Article");

        txtComptePrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 2, true));
        txtComptePrincipal.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtComptePrincipalCaretUpdate(evt);
            }
        });

        cmbSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BUREAU", "LIBARTICLE", "LIBETAT", "UTILISATEUR", "" }));
        cmbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSearchActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1617.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Critère:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtComptePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRechercher)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtComptePrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        ckBureau.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        ckBureau.setText("Par Bureau");
        ckBureau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckBureauActionPerformed(evt);
            }
        });

        ckTtInfo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        ckTtInfo.setText("Toutes les immobilisations");
        ckTtInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckTtInfoActionPerformed(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(204, 204, 0));
        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(255, 255, 255)));

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Proposition à la Reforme");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 485, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Immo", 1, 2, new java.awt.Font("Andalus", 1, 14))); // NOI18N

        jLabel1.setText("Article");

        jLabel4.setText("Bureau");

        jLabel5.setText("Montant Acqui");

        txtPrixresi.setEditable(false);

        jLabel7.setText("P résiduel");

        jLabel8.setText("Date M Service");

        jLabel9.setText("Date Proposition reforme");

        datepropoRef.setDateFormatString("dd/MM/yyyy");
        datepropoRef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datepropoRefMouseClicked(evt);
            }
        });
        datepropoRef.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datepropoRefPropertyChange(evt);
            }
        });

        dateMs.setDateFormatString("dd/MM/yyyy");

        jLabel10.setText("Durée vie");

        txtDurevie.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtDurevieCaretUpdate(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        jButton6.setText("Proposer en reforme");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateMs, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(txtBur, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(datepropoRef, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMontantacqui, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDurevie, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrixresi)
                                .addGap(31, 31, 31))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(419, 419, 419)
                                .addComponent(jButton6)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel8))
                    .addComponent(dateMs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel9))
                    .addComponent(datepropoRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMontantacqui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDurevie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txtPrixresi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(ckTtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ckBureau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(485, 485, 485))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(pnBureau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(269, 269, 269))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckTtInfo)
                    .addComponent(ckBureau))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnBureau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-919)/2, (screenSize.height-603)/2, 919, 603);
    }// </editor-fold>//GEN-END:initComponents

    private void chargement(){
        try {
            tableMaterielService.setModel(s.getDefaulTableModel(reqpart));
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    }
  
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try { 
           
            // chargement de combo
            alService = r.getComboELement("select idservice,LIBSERVICE from service order by LIBSERVICE",ComboSer);
            CodeService.setText(alService.get(ComboSer.getSelectedIndex()).toString());
             CodeBure.setText(null);
            alBureau=r.getComboELement("select idbureau,libbur from bureau where idservice="+CodeService.getText()+" order by libbur",comboBureau);
            
            CodeBure.setText(alBureau.get(comboBureau.getSelectedIndex()).toString());
           
            r.viderJtable(tableMaterielService);   
            // chargement();
             s.setRemplirJtable(tableMaterielService, reqpart+" and IMMOBILISATIONMATERIEL.IDBUREAU="+CodeBure.getText());
    } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
        dema=1;
       
    }//GEN-LAST:event_formComponentShown

    private void ComboSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboSerActionPerformed

        try {
            //Service.setText(ALSERVICE.get(ComboSer.getSelectedIndex()).toString());
            CodeService.setText(alService.get(ComboSer.getSelectedIndex()).toString());
            CodeBure.setText(null);
            alBureau=r.getComboELement("select idbureau,libbur from bureau where idservice="+CodeService.getText()+" order by libbur",comboBureau);
            CodeBure.setText(alBureau.get(comboBureau.getSelectedIndex()).toString());
             r.viderJtable(tableMaterielService);   
            // chargement();
             s.setRemplirJtable(tableMaterielService, reqpart+" and IMMOBILISATIONMATERIEL.IDBUREAU="+CodeBure.getText());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage());
        }
    }//GEN-LAST:event_ComboSerActionPerformed

    private void comboBureauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBureauActionPerformed
        CodeBure.setText(alBureau.get(comboBureau.getSelectedIndex()).toString());
        try {
         s.setRemplirJtable(tableMaterielService, reqpart+" and IMMOBILISATIONMATERIEL.IDBUREAU="+CodeBure.getText());       
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this,ex.getMessage());
        }       
    }//GEN-LAST:event_comboBureauActionPerformed

    private void CodeBureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeBureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodeBureActionPerformed

    private void txtComptePrincipalCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtComptePrincipalCaretUpdate
        if(txtComptePrincipal.getText()!=""){
                String a= cmbSearch.getSelectedItem().toString();
                if(a.equals("BUREAU"))
                    a="libbur";
            try {
                s.setRemplirJtable(tableMaterielService,reqpart+ " and "+a +" like '%"+txtComptePrincipal.getText()+"%'");
        } catch (SQLException ex) {
        }
        }
    }//GEN-LAST:event_txtComptePrincipalCaretUpdate

    private void cmbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSearchActionPerformed
        lblRechercher.setText(cmbSearch.getSelectedItem().toString());
    }//GEN-LAST:event_cmbSearchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ckTtInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckTtInfoActionPerformed
        if(ckTtInfo.getModel().isSelected()){
           ckBureau.getModel().setSelected(false);
         for(Component c:pnBureau.getComponents())
             c.setEnabled(false);
        }
    }//GEN-LAST:event_ckTtInfoActionPerformed

    private void ckBureauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckBureauActionPerformed
        ckTtInfo.getModel().setSelected(false);
        if(ckBureau.getModel().isSelected())
        for(Component c:pnBureau.getComponents())
             c.setEnabled(true);   
    }//GEN-LAST:event_ckBureauActionPerformed
    private void montantResiduel(){
      try{
          if((datepropoRef.getDate()).before(a.addYear(dateMs.getDate(),dureevie))){
              //  JOptionPane.showMessageDialog(this,a.getNombreJour(dateMs.getDate(),dateRef.getDate()));
                 txtPrixresi.setText(a.formatageMontant(a.getValeurBienN(dureevie,a.getNombreJour(dateMs.getDate(),datepropoRef.getDate()),Float.valueOf(a.parseMontantFomatToString(txtMontantacqui.getText())))));
            }
              
            else
                 txtPrixresi.setText("0");
      }catch(ParseException ex){
          JOptionPane.showMessageDialog(this,ex.getMessage());
      }
    }
    private void tableMaterielServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMaterielServiceMouseClicked
            idimmo=tableMaterielService.getValueAt(tableMaterielService.getSelectedRow(),s.getColumnByName(tableMaterielService,"idimmobilisationmateriel")).toString();
            txtArticle.setText(tableMaterielService.getValueAt(tableMaterielService.getSelectedRow(),s.getColumnByName(tableMaterielService,"article")).toString());   
            txtBur.setText(tableMaterielService.getValueAt(tableMaterielService.getSelectedRow(),s.getColumnByName(tableMaterielService,"bureau")).toString());
            JOptionPane.showMessageDialog(this, "montant est "+a.formatageMontant(tableMaterielService.getValueAt(tableMaterielService.getSelectedRow(),s.getColumnByName(tableMaterielService,"puacq"))));
            txtMontantacqui.setText(a.formatageMontant(tableMaterielService.getValueAt(tableMaterielService.getSelectedRow(),s.getColumnByName(tableMaterielService,"puacq")).toString())); 
        try {
            r.setAfficherDate(dateMs, tableMaterielService.getValueAt(tableMaterielService.getSelectedRow(),s.getColumnByName(tableMaterielService,"dms")).toString());
        } catch (ParseException ex) {
          JOptionPane.showMessageDialog(this,ex.getMessage());
        }
            datepropoRef.setDate(new Date());      
            txtDurevie.setText(tableMaterielService.getValueAt(tableMaterielService.getSelectedRow(),s.getColumnByName(tableMaterielService,"dureevie")).toString());
            montantResiduel();
               
            
           // txtPrixresi
          
      
    }//GEN-LAST:event_tableMaterielServiceMouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        try {
            s.setRemplirJtable(tableMaterielService, reqpart+" and IMMOBILISATIONMATERIEL.IDBUREAU="+CodeBure.getText());
        } catch (SQLException ex) {
            Logger.getLogger(NouveauPropositionReforme.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void datepropoRefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datepropoRefMouseClicked
      // TODO add your handling code here:
    }//GEN-LAST:event_datepropoRefMouseClicked
     int dureevie=0;
    private void datepropoRefPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datepropoRefPropertyChange
     if (dema==1){ 
      if(datepropoRef.getDate().before(dateMs.getDate())){
          JOptionPane.showMessageDialog(this,"date de réforme inférieur à date de mise en service\n calcul de prix impossible");
          txtPrixresi.setText(null);
          dema=0;
      }
      else
      montantResiduel();
     }
    }//GEN-LAST:event_datepropoRefPropertyChange

    private void txtDurevieCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtDurevieCaretUpdate
      try{
          if(!txtDurevie.getText().isEmpty())
        dureevie=Integer.parseInt(txtDurevie.getText());      
       montantResiduel();
      }catch(Exception exe){
          JOptionPane.showMessageDialog(this,"la durée doit être un nombre");
      }
    }//GEN-LAST:event_txtDurevieCaretUpdate

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
 if(txtArticle.getText().isEmpty())
        JOptionPane.showMessageDialog(this,"choisissez une immobilisation à reformer");
        else if(txtPrixresi.getText().isEmpty())
        JOptionPane.showMessageDialog(this,"prix résiduel non renseigné");
        else{
            int reponse= JOptionPane.showConfirmDialog(this,"voulez-vous enregistrez la réforme?","confirmation",JOptionPane.YES_NO_OPTION);
            if(reponse==JOptionPane.YES_OPTION){
                try {
                    String champ[]={"prixresiduel","dateproporef","situationmateriel"};
                     String valeur[]={a.parseMontantFomatToString(txtPrixresi.getText()),r.getDateChoisie(datepropoRef),"enreforme"};
                    int i=r.updateTable("immobilisationmateriel",champ,valeur," where idimmobilisationmateriel="+idimmo);
                    JOptionPane.showMessageDialog(this, i+" réforme proposée");
                    if(i==1){
                        txtArticle.setText(null);
                        txtPrixresi.setText(null);
                        //txtDurevie.setText(null);
                        txtMontantacqui.setText(null);
                        dateMs.setDate(null);
                        // dateRef.setDate(null);
                        txtBur.setText(null);   
                        txtPrixresi.setText(null);

                    }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this,ex.getMessage());
                }

            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NouveauPropositionReforme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NouveauPropositionReforme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NouveauPropositionReforme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NouveauPropositionReforme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NouveauPropositionReforme dialog = new NouveauPropositionReforme(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodeBure;
    private javax.swing.JTextField CodeService;
    private javax.swing.JComboBox ComboSer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JCheckBox ckBureau;
    private javax.swing.JCheckBox ckTtInfo;
    private javax.swing.JComboBox cmbSearch;
    private javax.swing.JComboBox comboBureau;
    private com.toedter.calendar.JDateChooser dateMs;
    private com.toedter.calendar.JDateChooser datepropoRef;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRechercher;
    private javax.swing.JPanel pnBureau;
    private javax.swing.JTable tableMaterielService;
    private javax.swing.JTextField txtArticle;
    private javax.swing.JTextField txtBur;
    private javax.swing.JTextField txtComptePrincipal;
    private javax.swing.JTextField txtDurevie;
    private javax.swing.JTextField txtMontantacqui;
    private javax.swing.JTextField txtPrixresi;
    // End of variables declaration//GEN-END:variables
}
