/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formulaire.Sortie;

import comptamatiere.ARTICLE;
import comptamatiere.BON;
import comptamatiere.DETAILSORTIE;
import comptamatiere.SORTIE;
import control.Controle;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Nouveau extends javax.swing.JDialog {
    ARTICLE article = new ARTICLE();
    DETAILSORTIE d= new DETAILSORTIE();
    SORTIE sortie = new SORTIE();
    DefaultTableModel Model = new DefaultTableModel();
    int stock=0;
    ArrayList alBg,alS,alBu;
    BON b = new BON();
    String serv,bur,idbu;
    
    public Nouveau(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel12 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        tabBondesortie = new javax.swing.JTabbedPane();
        tabDemande = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        DateSortie = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        cmbService = new javax.swing.JComboBox();
        codeService = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cmbBureau = new javax.swing.JComboBox();
        codeBureau = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        tabBon = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableArticle = new javax.swing.JTable();
        txtComptePrincipal = new javax.swing.JTextField();
        lblRechercher = new javax.swing.JLabel();
        cmbSearch = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtarticle = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtQte = new javax.swing.JTextField();
        txtiddetailbon = new javax.swing.JTextField();
        StockA = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtQtenonvalide = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        Ajouter = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableDetail = new javax.swing.JTable();
        retirer = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnEnregistrer = new javax.swing.JButton();

        jPanel12.setBackground(new java.awt.Color(0, 0, 51));
        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(972, 630));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(0, 51, 51));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(255, 255, 255)));

        jLabel24.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Fiche Enregistrement");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabBondesortie.setBackground(new java.awt.Color(204, 255, 204));
        tabBondesortie.setPreferredSize(new java.awt.Dimension(400, 300));
        tabBondesortie.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabBondesortieComponentShown(evt);
            }
        });

        tabDemande.setBackground(new java.awt.Color(255, 255, 255));
        tabDemande.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Ordre de Sortie", 0, 0, null, new java.awt.Color(153, 153, 153)));
        tabDemande.setMaximumSize(new java.awt.Dimension(300, 300));
        tabDemande.setPreferredSize(new java.awt.Dimension(200, 150));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Demande", 1, 2, new java.awt.Font("Vivaldi", 1, 18), new java.awt.Color(204, 0, 51))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(400, 267));

        DateSortie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateSortieMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel14.setText("Service");

        cmbService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbServiceActionPerformed(evt);
            }
        });

        codeService.setEditable(false);
        codeService.setForeground(new java.awt.Color(255, 0, 0));
        codeService.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                codeServiceCaretUpdate(evt);
            }
        });
        codeService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeServiceActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel15.setText("Bureau");

        cmbBureau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBureauActionPerformed(evt);
            }
        });

        codeBureau.setEditable(false);
        codeBureau.setForeground(new java.awt.Color(255, 0, 0));
        codeBureau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeBureauActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel18.setText("Date");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbBureau, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbService, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeService, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeBureau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(158, 158, 158))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(DateSortie, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbService, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codeService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbBureau, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codeBureau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateSortie, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jButton2.setText("Suivant->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabDemandeLayout = new javax.swing.GroupLayout(tabDemande);
        tabDemande.setLayout(tabDemandeLayout);
        tabDemandeLayout.setHorizontalGroup(
            tabDemandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDemandeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        tabDemandeLayout.setVerticalGroup(
            tabDemandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDemandeLayout.createSequentialGroup()
                .addGroup(tabDemandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDemandeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabDemandeLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        tabBondesortie.addTab("Demande", tabDemande);

        tabBon.setBackground(new java.awt.Color(255, 255, 255));
        tabBon.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabBonComponentShown(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Articles", 0, 0, null, new java.awt.Color(0, 0, 0)));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setText("Rechercher Par");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        tableArticle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableArticle.setEditingRow(0);
        tableArticle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableArticleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableArticle);

        txtComptePrincipal.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtComptePrincipalCaretUpdate(evt);
            }
        });
        txtComptePrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComptePrincipalActionPerformed(evt);
            }
        });

        lblRechercher.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRechercher.setText("Article");

        cmbSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Article" }));
        cmbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(lblRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtComptePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtComptePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel6.setText("Article");

        txtCode.setEditable(false);
        txtCode.setBackground(new java.awt.Color(255, 255, 255));

        txtarticle.setEditable(false);
        txtarticle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel7.setText("Qté à sortir");

        txtQte.setBackground(new java.awt.Color(240, 240, 240));
        txtQte.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtQte.setForeground(new java.awt.Color(255, 0, 0));
        txtQte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQteActionPerformed(evt);
            }
        });
        txtQte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQteFocusLost(evt);
            }
        });
        txtQte.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtQteInputMethodTextChanged(evt);
            }
        });

        txtiddetailbon.setEditable(false);
        txtiddetailbon.setBackground(new java.awt.Color(255, 255, 255));

        StockA.setEditable(false);
        StockA.setBackground(new java.awt.Color(153, 255, 204));

        jLabel20.setText("Stok A");

        txtQtenonvalide.setEditable(false);
        txtQtenonvalide.setBackground(new java.awt.Color(255, 204, 51));
        jScrollPane4.setViewportView(txtQtenonvalide);

        jLabel1.setText("Qte non Validé");

        Ajouter.setBackground(new java.awt.Color(204, 0, 51));
        Ajouter.setText("Ajouter");
        Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtarticle)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane4))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(StockA, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQte, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(txtiddetailbon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtiddetailbon, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtarticle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StockA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel7)
                    .addComponent(txtQte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Sortie"));

        TableDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Titre 5"
            }
        ));
        jScrollPane2.setViewportView(TableDetail);
        TableDetail.getColumnModel().getColumn(0).setResizable(false);
        TableDetail.getColumnModel().getColumn(0).setPreferredWidth(0);
        TableDetail.getColumnModel().getColumn(1).setResizable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        retirer.setText("Retirer");
        retirer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirerActionPerformed(evt);
            }
        });

        jButton6.setText("<- Retour");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnEnregistrer.setBackground(new java.awt.Color(51, 255, 204));
        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabBonLayout = new javax.swing.GroupLayout(tabBon);
        tabBon.setLayout(tabBonLayout);
        tabBonLayout.setHorizontalGroup(
            tabBonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tabBonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabBonLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(retirer, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnEnregistrer))
                    .addGroup(tabBonLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(91, 91, 91))
            .addGroup(tabBonLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tabBonLayout.setVerticalGroup(
            tabBonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBonLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabBonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabBonLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                        .addGap(231, 231, 231))
                    .addGroup(tabBonLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(tabBonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retirer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );

        tabBondesortie.addTab("Bon de Sortie", tabBon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabBondesortie, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabBondesortie, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-759)/2, (screenSize.height-493)/2, 759, 493);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(codeBureau.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "Choisissez le bureau");
        else if(DateSortie.getDate()==null)
        JOptionPane.showMessageDialog(this,"La date de sortie est vide");
        else
        tabBondesortie.setSelectedIndex(tabBondesortie.getSelectedIndex()+1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void DateSortieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateSortieMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DateSortieMouseClicked

    private void cmbServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbServiceActionPerformed
        codeService.setText(alS.get(cmbService.getSelectedIndex()).toString());
        try {
            // alBu.clear();
            alBu=b.getComboELement("select idbureau,libbur from bureau where idservice="+codeService.getText(), cmbBureau);
            if(cmbBureau.getSelectedIndex()!=-1)
            codeBureau.setText(alBu.get(cmbBureau.getSelectedIndex()).toString());
            else
            codeBureau.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"1-:"+ex.getMessage());
        }

    }//GEN-LAST:event_cmbServiceActionPerformed

    private void codeServiceCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_codeServiceCaretUpdate

    }//GEN-LAST:event_codeServiceCaretUpdate

    private void codeServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeServiceActionPerformed

    }//GEN-LAST:event_codeServiceActionPerformed

    private void cmbBureauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBureauActionPerformed
        codeBureau.setText(alBu.get(cmbBureau.getSelectedIndex()).toString());
    }//GEN-LAST:event_cmbBureauActionPerformed

    private void codeBureauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeBureauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeBureauActionPerformed

    private void tableArticleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableArticleMouseClicked
        txtarticle.setText("");
        txtCode.setText("");
        StockA.setText("");
        txtQte.setText("");
        //recuperation de id de l article
        int codeA= Integer.parseInt(tableArticle.getValueAt(tableArticle.getSelectedRow(), article.getColumnByName(tableArticle,"Code")).toString());
        try {
            //recuperation des qte non valide de l article concerne et affecté au champ qtenonvalide
            txtQtenonvalide.setText(Integer.toString(article.getQteSortiNonValide(codeA)));
        } catch (SQLException ex) {
            Logger.getLogger(Nouveau.class.getName()).log(Level.SEVERE, null, ex);
        }
            //recuperation de la quantite théorique sans prendre en compte les sorties non validées 
           int Stocktheorique=Integer.parseInt(tableArticle.getValueAt(tableArticle.getSelectedRow(), d.getColumnByName(tableArticle, "Stock")).toString());
           //reste de la quantité possible de sortir
           int rest=Stocktheorique-Integer.parseInt(txtQtenonvalide.getText());
            StockA.setText(Integer.toString(rest));
           
         txtCode.setText(tableArticle.getValueAt(tableArticle.getSelectedRow(),d.getColumnByName(tableArticle, "Code")).toString());
        //txtarticle.setHorizontalAlignment(txtarticle.CENTER);
        txtarticle.setText(tableArticle.getValueAt(tableArticle.getSelectedRow(), d.getColumnByName(tableArticle, "Article")).toString());
        txtQte.setFocusable(true);
    }//GEN-LAST:event_tableArticleMouseClicked

    private void txtQteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQteActionPerformed

    }//GEN-LAST:event_txtQteActionPerformed

    private void txtQteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQteFocusLost
        // TODO add your handling code here:
        if((Integer.parseInt("0"+txtQte.getText()))>(Integer.parseInt("0"+StockA.getText()))){
            JOptionPane.showMessageDialog(this,(Integer.parseInt(StockA.getText())),"Comptabilté Matiere",3);
        }
    }//GEN-LAST:event_txtQteFocusLost

    private void txtQteInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtQteInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQteInputMethodTextChanged

    private void AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterActionPerformed
        if(txtQte.getText().isEmpty())
        JOptionPane.showMessageDialog(this,"Saisissez la quantité à sortir");
        else if(Integer.parseInt(txtQte.getText())>Integer.parseInt(StockA.getText()))
        JOptionPane.showMessageDialog(this,"La quantité demandée ne peut être servie");
        else if(Integer.parseInt(StockA.getText())-Integer.parseInt(txtQtenonvalide.getText())<=0)
            JOptionPane.showMessageDialog(this,"cet article n\'est plus disponible dans le stock");
        else{
            // d.sortieParLot(tableLot, TableArticle, txtQte.getText(), txtCode.getText(), txtarticle.getText());
            int rest=Integer.parseInt(txtQte.getText());
            int test=Integer.parseInt(txtQte.getText());
                    Object[] Obj = {txtCode.getText(), txtarticle.getText(),txtQte.getText()};
                    Model.addRow(Obj);
                    TableDetail.setModel(Model);
                    //quantité article dejà sortie
            }
            int retour=Integer.parseInt(StockA.getText())-Integer.parseInt(txtQte.getText());
            tableArticle.setValueAt(retour, tableArticle.getSelectedRow(),d.getColumnByName(tableArticle, "Stock"));//mise ajour de la cellule qte de l article servi
            
            txtarticle.setText("");
            txtCode.setText("");
            txtQte.setText("");
            StockA.setText("");
    }//GEN-LAST:event_AjouterActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tabBondesortie.getSelectedIndex();
        selectedIndex = (selectedIndex - 1) % tabBondesortie.getTabCount();
        tabBondesortie.setSelectedIndex(selectedIndex);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void retirerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirerActionPerformed
        //recuperation codearticle a retiere
        int CodeArticle=Integer.parseInt(TableDetail.getValueAt(TableDetail.getSelectedRow(),b.getColumnByName(TableDetail, "code")).toString());
        //recuperation qte a retiere
        int Qte=Integer.parseInt(TableDetail.getValueAt(TableDetail.getSelectedRow(),b.getColumnByName(TableDetail, "qte")).toString());
         //recuperation de la ligne concernee dans table article je precise la l indexe de la colonne codearticle dans tablearticle
        int ligne=b.getRowByCode(tableArticle,0, CodeArticle);
        JOptionPane.showMessageDialog(this, ligne);
        ((DefaultTableModel) TableDetail.getModel()).removeRow(TableDetail.getSelectedRow());
         int retirer=0;
            // Integer.parseInt(TableDetail.getValueAt(TableDetail.getSelectedRow(),d.getColumnByName(TableDetail, "r")).toString()),
                                //valeur         ligne                             colonne
        tableArticle.setValueAt(retirer,d.getRowByCode(tableArticle,0,1),d.getColumnByName(tableArticle, "Stock"));
    }//GEN-LAST:event_retirerActionPerformed

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        if(TableDetail.getRowCount()==0)
        JOptionPane.showMessageDialog(this,"choisissez les biens à sortir");
        else{
            //enregistrement de la sortie
            int reponse = JOptionPane.showConfirmDialog(this, "voulez-vous enregistrez?", "confirmation", JOptionPane.YES_NO_OPTION);
            if (reponse == JOptionPane.YES_OPTION) {
                try {
                    String valeur[] = {codeBureau.getText(),sortie.getDateChoisie(DateSortie)};
                    int i = sortie.Insertion("SORTIE(idBUREAU,NUMPJ,DATESORTIE,budget,ATITRE,OBJET,MOTIF)", valeur);
                    JOptionPane.showMessageDialog(this,i+" bon de sortie enrégistré");
                    int g=0;
                    int totalSortie=0;
                    String idSortie=b.getOneResult("select max(idsortie) from sortie");

                    //enregistrement du detail sortie
                    int immo;
                    int codegenre=0;
                    for (int k=0; k< TableDetail.getRowCount();k++){
                        String iddetailbon=TableDetail.getValueAt(k,b.getColumnByName(TableDetail, "Ligne")).toString();
                        String qte=TableDetail.getValueAt(k,b.getColumnByName(TableDetail, "qte")).toString();
                        String pu= TableDetail.getValueAt(k,b.getColumnByName(TableDetail, "pu")).toString();
                       String idarticle=TableDetail.getValueAt(k,b.getColumnByName(TableDetail, "code")).toString();
                        String type=TableDetail.getValueAt(k,b.getColumnByName(TableDetail, "Type")).toString();
                       
                       //JOptionPane.showMessageDialog(this, idarticle + " article(s) du bon N°"+idSortie+" engistré(s)");
                       /*je prend le numero de compte de la categorie à laquelle appartient l article,je verifie si cest compri entre 24000 et 24999 alors cest une immo=1*/
                       String numerocompte=b.getOneResult("select numerocompte from article,categorie where article.idarticle="+idarticle+" and article.idcategorie=categorie.idcategorie");
                       if ((Integer.parseInt(numerocompte)>=24000)&&( Integer.parseInt(numerocompte)<24999)){
                           immo=1;
                       }else{
                           immo=0;
                       }
                        String valeurD[]={iddetailbon,qte,pu,idSortie,Integer.toString(immo),Integer.toString(codegenre),idarticle,qte,type};
                        sortie.Insertion("DETAILSORTIE(idDETAILBON,QTE_SORTIE,PU_SORTIE,idSortie,immo,codegenere,idarticle,nonattribue,type)", valeurD);
                        g++;
                        totalSortie=totalSortie+Integer.parseInt(qte);
                    }
                    JOptionPane.showMessageDialog(this, g + " article(s) du bon N°"+idSortie+" engistré(s)");
                    Controle.modification=true;
                    sortie.viderJtable(TableDetail);
                    //impression de bon de sortie
                    reponse=JOptionPane.showConfirmDialog(this, "Imprimer ordre de sortie?","impression état",JOptionPane.YES_NO_OPTION);
                    if(reponse==JOptionPane.YES_OPTION)
                    sortie.printReport(idSortie);
                    btnEnregistrer.setEnabled(false);
                }catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "2-"+ex.getMessage());
                }catch (Exception ex) {
                    JOptionPane.showMessageDialog(this,"3-"+ ex.getMessage());
                }

            }
        }
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void tabBonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabBonComponentShown

    }//GEN-LAST:event_tabBonComponentShown

    private void tabBondesortieComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabBondesortieComponentShown

    }//GEN-LAST:event_tabBondesortieComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
  
        try { 
                tableArticle.setModel(article.getDefaulTableModel("select iDARTICLE as Code,libcategorie as Categorie, libarticle as Article,article.STOCKACTU as Stock,PRIXUNITAIRE as Pu FROM ARTICLE,CATEGORIE WHERE ARTICLE.IDCATEGORIE=CATEGORIE.IDCATEGORIE "));
                alS=b.getComboELement("select idservice,serv from service order by serv", cmbService);
                codeService.setText(alS.get(cmbService.getSelectedIndex()).toString());
                String[] tab = {"Code", "Article", "Qte"};
                Model.setColumnIdentifiers(tab);
                TableDetail.setModel(Model); 
                
                
             TableDetail.getColumn("Code").setMinWidth(0);
             TableDetail.getColumn("Code").setPreferredWidth(0);
             TableDetail.getColumn("Code").setMaxWidth(0);
             
             TableDetail.getColumn("Ligne").setMinWidth(0);
             TableDetail.getColumn("Ligne").setPreferredWidth(0);
             TableDetail.getColumn("Ligne").setMaxWidth(0);
             
              TableDetail.getColumn("Type").setMinWidth(0);
             TableDetail.getColumn("Type").setPreferredWidth(0);
             TableDetail.getColumn("Type").setMaxWidth(0);
             
             TableDetail.getColumn("Qte").setMinWidth(65);
             TableDetail.getColumn("Qte").setPreferredWidth(65);
             TableDetail.getColumn("Qte").setMaxWidth(65);
             
             TableDetail.getColumn("PU").setMinWidth(95);
             TableDetail.getColumn("PU").setPreferredWidth(95);
             TableDetail.getColumn("PU").setMaxWidth(95);
                // codeService.setText(alS.get(cmbService.getSelectedIndex()).toString());
              txtarticle.setHorizontalAlignment(txtarticle.CENTER); // setHorizontalAlignment
              
              
             tableArticle.getColumn("Code").setMinWidth(0);
             tableArticle.getColumn("Code").setPreferredWidth(0);
             tableArticle.getColumn("Code").setMaxWidth(0);
             
             tableArticle.getColumn("Categorie").setMinWidth(180);
             tableArticle.getColumn("Categorie").setPreferredWidth(180);
             tableArticle.getColumn("Categorie").setMaxWidth(180);
             
             tableArticle.getColumn("Stock").setMinWidth(65);
             tableArticle.getColumn("Stock").setPreferredWidth(65);
             tableArticle.getColumn("Stock").setMaxWidth(65);
             tableArticle.getColumn("Pu").setMinWidth(95);
             tableArticle.getColumn("Pu").setPreferredWidth(95);
             tableArticle.getColumn("Pu").setMaxWidth(95);
        try {
            // alBu.clear();
            if(!codeService.getText().isEmpty())     
            alBu=b.getComboELement("select idbureau,libbur from bureau where idservice="+codeService.getText(),cmbBureau);
            if(cmbBureau.getSelectedIndex()!=-1)
            codeBureau.setText(alBu.get(cmbBureau.getSelectedIndex()).toString());
            else
            codeBureau.setText("");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"5-"+ex.getMessage());
        } 
                //desactivation des tab
                 tabBondesortie.setEnabledAt(1,false);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"4-"+ ex.getMessage());
        }           
    }//GEN-LAST:event_formComponentShown

    private void txtComptePrincipalCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtComptePrincipalCaretUpdate
        if(txtComptePrincipal.getText()!=""){
            try {
               // tableArticle.getColumnModel().getColumn(0).setPreferredWidth(2);
             
                //tableArticle.getColumnModel().getColumn(0).setPreferredWidth(2);
                 String art=cmbSearch.getSelectedItem().toString();
                if(art.equalsIgnoreCase("Article"))
                    art="libarticle";

                tableArticle.setModel(article.getDefaulTableModel("select iDARTICLE as Code,libcategorie as Categorie, libarticle as Article,STOCKACTU as Stock,PRIXUNITAIRE as Pu FROM ARTICLE,CATEGORIE WHERE ARTICLE.IDCATEGORIE=CATEGORIE.IDCATEGORIE  and "+art+" like '%"+txtComptePrincipal.getText()+"%'"));
               } catch (SQLException ex) {
            }
        }
            
             tableArticle.getColumn("Code").setMinWidth(0);
             tableArticle.getColumn("Code").setPreferredWidth(0);
             tableArticle.getColumn("Code").setMaxWidth(0);
             
             tableArticle.getColumn("Categorie").setMinWidth(180);
             tableArticle.getColumn("Categorie").setPreferredWidth(180);
             tableArticle.getColumn("Categorie").setMaxWidth(180);
             
             tableArticle.getColumn("Stock").setMinWidth(65);
             tableArticle.getColumn("Stock").setPreferredWidth(65);
             tableArticle.getColumn("Stock").setMaxWidth(65);
             tableArticle.getColumn("Pu").setMinWidth(95);
             tableArticle.getColumn("Pu").setPreferredWidth(95);
             tableArticle.getColumn("Pu").setMaxWidth(95);

    }//GEN-LAST:event_txtComptePrincipalCaretUpdate

    private void txtComptePrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComptePrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComptePrincipalActionPerformed

    private void cmbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSearchActionPerformed
        lblRechercher.setText(cmbSearch.getSelectedItem().toString());
    }//GEN-LAST:event_cmbSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nouveau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nouveau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nouveau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nouveau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Nouveau dialog = new Nouveau(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ajouter;
    private com.toedter.calendar.JDateChooser DateSortie;
    private javax.swing.JTextField StockA;
    private javax.swing.JTable TableDetail;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JComboBox cmbBureau;
    private javax.swing.JComboBox cmbSearch;
    private javax.swing.JComboBox cmbService;
    private javax.swing.JTextField codeBureau;
    private javax.swing.JTextField codeService;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblRechercher;
    private javax.swing.JButton retirer;
    private javax.swing.JPanel tabBon;
    private javax.swing.JTabbedPane tabBondesortie;
    private javax.swing.JPanel tabDemande;
    private javax.swing.JTable tableArticle;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtComptePrincipal;
    private javax.swing.JTextField txtQte;
    private javax.swing.JTextPane txtQtenonvalide;
    private javax.swing.JTextField txtarticle;
    private javax.swing.JTextField txtiddetailbon;
    // End of variables declaration//GEN-END:variables
}
